// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_CliApi_cliente from "./routes/api/CliApi/cliente.ts";
import * as $api_ProyApi_arquitectoGet from "./routes/api/ProyApi/arquitectoGet.ts";
import * as $api_ProyApi_proyectos from "./routes/api/ProyApi/proyectos.ts";
import * as $api_arquitectoRegister from "./routes/api/arquitectoRegister.ts";
import * as $api_arquitectoSesions from "./routes/api/arquitectoSesions.ts";
import * as $api_arquitectoUpdate from "./routes/api/arquitectoUpdate.ts";
import * as $api_cliente from "./routes/api/cliente.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_registro from "./routes/api/registro.ts";
import * as $api_sessions from "./routes/api/sessions.ts";
import * as $index from "./routes/index.tsx";
import * as $proyectos_create from "./routes/proyectos/create.tsx";
import * as $proyectos_index from "./routes/proyectos/index.tsx";
import * as $proyectos_list_id_ from "./routes/proyectos/list/[id].tsx";
import * as $register from "./routes/register.tsx";
import * as $sesion_login from "./routes/sesion/login.tsx";
import * as $sesion_logout from "./routes/sesion/logout.ts";
import * as $CartPres from "./islands/CartPres.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $FormArquitectoRegister from "./islands/FormArquitectoRegister.tsx";
import * as $FormLogin from "./islands/FormLogin.tsx";
import * as $FormRegister from "./islands/FormRegister.tsx";
import * as $MainIsland from "./islands/MainIsland.tsx";
import * as $NavBar from "./islands/NavBar.tsx";
import * as $ProyNew from "./islands/ProyNew.tsx";
import * as $ProyView from "./islands/ProyView.tsx";
import * as $ProyViewID from "./islands/ProyViewID.tsx";
import * as $SiderBar from "./islands/SiderBar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/CliApi/cliente.ts": $api_CliApi_cliente,
    "./routes/api/ProyApi/arquitectoGet.ts": $api_ProyApi_arquitectoGet,
    "./routes/api/ProyApi/proyectos.ts": $api_ProyApi_proyectos,
    "./routes/api/arquitectoRegister.ts": $api_arquitectoRegister,
    "./routes/api/arquitectoSesions.ts": $api_arquitectoSesions,
    "./routes/api/arquitectoUpdate.ts": $api_arquitectoUpdate,
    "./routes/api/cliente.ts": $api_cliente,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/registro.ts": $api_registro,
    "./routes/api/sessions.ts": $api_sessions,
    "./routes/index.tsx": $index,
    "./routes/proyectos/create.tsx": $proyectos_create,
    "./routes/proyectos/index.tsx": $proyectos_index,
    "./routes/proyectos/list/[id].tsx": $proyectos_list_id_,
    "./routes/register.tsx": $register,
    "./routes/sesion/login.tsx": $sesion_login,
    "./routes/sesion/logout.ts": $sesion_logout,
  },
  islands: {
    "./islands/CartPres.tsx": $CartPres,
    "./islands/Counter.tsx": $Counter,
    "./islands/FormArquitectoRegister.tsx": $FormArquitectoRegister,
    "./islands/FormLogin.tsx": $FormLogin,
    "./islands/FormRegister.tsx": $FormRegister,
    "./islands/MainIsland.tsx": $MainIsland,
    "./islands/NavBar.tsx": $NavBar,
    "./islands/ProyNew.tsx": $ProyNew,
    "./islands/ProyView.tsx": $ProyView,
    "./islands/ProyViewID.tsx": $ProyViewID,
    "./islands/SiderBar.tsx": $SiderBar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
