// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_cliente from "./routes/api/cliente.ts";
import * as $api_login from "./routes/api/login.tsx";
import * as $api_session from "./routes/api/session.ts";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $CataContainer from "./islands/CataContainer.tsx";
import * as $Footer from "./islands/Footer.tsx";
import * as $Login from "./islands/Login.tsx";
import * as $NavBar from "./islands/NavBar.tsx";
import * as $PagInicio_ContMain from "./islands/PagInicio/ContMain.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/cliente.ts": $api_cliente,
    "./routes/api/login.tsx": $api_login,
    "./routes/api/session.ts": $api_session,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/CataContainer.tsx": $CataContainer,
    "./islands/Footer.tsx": $Footer,
    "./islands/Login.tsx": $Login,
    "./islands/NavBar.tsx": $NavBar,
    "./islands/PagInicio/ContMain.tsx": $PagInicio_ContMain,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
